# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: 张玉龙的博客
name: 张玉龙
email: admin@iwenli.org
location: 北京，中国
company: 自由职业者
company_url: http://iwenli.org
github_url: https://github.com/iwenli
description: 张玉龙的博客
favicon: favicon.ico # Image must be in assets/images
repository: iwenli/iwenli.github.io
encoding: utf-8

url: http://blog.iwenli.org # the base hostname & protocol for your site

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: false

# Navigation
navs:
  -
    href: /
    label: 主页
    pattern: Home

  -
    href: /open-source
    label: 开源项目
    pattern: Open Source Projects

  -
    href: /blog-cn
    label: 博客
    pattern: All My Blogs

  -
    href: /about
    label: 简介
    pattern: About

# Pagination
paginate: 10
paginate_path: 'page:num'

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Disqus Comments
disqus: crazyzty.disqus.com

# Google Analytics
analytics :
  provider : google
  google :
    tracking_id : 'UA-92426808-1'

# For about.html. Fell free to create your own!
skill_software_keywords: [C#, .Net, C, MySQL, SQLite, Node.js, Design Patterns]
skill_web_keywords: [HTML, CSS, JavaScript, JQuery, Ajax, ASP.NET]
skill_mobile_app_keywords: [Android]
