# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
<<<<<<< HEAD
title:张玉龙的博客
name: 张玉龙
email: admin@iwenli.org
location: 北京，中国
company: 自由职业者
company_url: http://iwenli.org
github_url: https://github.com/iwenli
description: 张玉龙的博客
favicon: favicon.ico # Image must be in assets/images
repository: iwenli/iwenli.github.io
encoding: utf-8

url: http://blog.iwenli.org # the base hostname & protocol for your site
=======
title: Yummy Theme # ex. I m Chuan
name: Your Name # ex. DONGChuan
email: my_email_address@lalala.com
location: My location # ex. Nice, France
company: MyCompany
company_url: my_company_website
github_url: my_github_url # ex. https://github.com/DONGChuan
description: description_of_your_web_site
favicon: favicon.png # Image must be in assets/images
repository: github_username/github_username.github.io # ex. DONGChuan/DONGChuan.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: http://localhost:4000
>>>>>>> 5b15e9df575df802766046b31a03e3b2d3a24cef

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
<<<<<<< HEAD
  enable_coderay: false

# Navigation
navs:
  -
    href: /
    label: 主页
    pattern: Home

  -
    href: /open-source
    label: 开源项目
    pattern: Open Source Projects

  -
    href: /blog
    label: 博客
    pattern: All My Blogs

  -
    href: /about
    label: 简介
    pattern: About

# Pagination
paginate: 10
paginate_path: 'page:num'
=======
  enable_coderay: true

# Disque
disque: my_disque_settings # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: /blog
    label: Blog

  -
    href: /bookmark
    label: Bookmark

  -
    href: /about
    label: About
>>>>>>> 5b15e9df575df802766046b31a03e3b2d3a24cef

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

<<<<<<< HEAD
# Disqus Comments
disqus: crazyzty.disqus.com

=======
>>>>>>> 5b15e9df575df802766046b31a03e3b2d3a24cef
# Google Analytics
analytics :
  provider : google
  google :
<<<<<<< HEAD
    tracking_id : 'UA-92426808-1'

# For about.html. Fell free to create your own!
skill_software_keywords: [C#, .Net, C, MySQL, SQLite, Node.js, Design Patterns]
skill_web_keywords: [HTML, CSS, JavaScript, JQuery, Ajax, ASP.NET]
skill_mobile_app_keywords: [Android]
=======
      tracking_id : 'tracking_id'  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, C, C++, Qt, Python, MySQL, Oracle, SQLite, PL/SQL, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, AngularJS, NodeJS, ExpressJS, MongoDB, Redis, PHP, Symfony, Boostrap]
skill_mobile_app_keywords: [Android, Sketch UI Desgin]
>>>>>>> 5b15e9df575df802766046b31a03e3b2d3a24cef
